version: '3.4'

services:
  api:
    command: npm run watch
    volumes:
      - ./src:/node/src
      - ./__tests__:/node/__tests__
      - ./__fixtures__:/node/__fixtures__
      - ./migrations:/node/migrations

    ports:
      - "9229:9229"
