version: '3.4'

services:
  api:
    build: api

    environment:
      - PORT
      - NODE_ENV
      - JWKS_AUD
      - JWKS_HOST
      - DATABASE_URL
      - AUTH0_CLIENT_ID
      - AUTH0_DOMAIN_URL
      - AUTH0_REDIRECT_URL
      - AUTH0_CLIENT_SECRET
      - AUTH0_USERS_CLIENT_ID
      - AUTH0_USERS_CLIENT_SECRET
      - GOOGLE_PLACES_API_KEY
      - STREAMJS_APP_ID
      - STREAMJS_API_KEY
      - STREAMJS_API_SECRET

    ports:
      - "8080:8080"

  db:
    build: db

    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_TEST_DB
      - POSTGRES_PASSWORD
